FROM wordpress:php7.4-apache

# Syncronize permissions: give the container user (www-data) the same UID and GID as your host user (in archilinux is 1000)
ARG user_id=1000
RUN usermod -u $user_id www-data
RUN groupmod -g $user_id www-data
# Change permissions on the whole project folder 

RUN chmod -R g+r /var/www/html/

USER www-data

#CMD ["apache2-foreground"]